-- Create tables for stevens-transport-app
CREATE TABLE IF NOT EXISTS "applications" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "middleName" TEXT,
    "socialSecurity" TEXT NOT NULL,
    "dateOfBirth" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "alternatePhone" TEXT,
    "email" TEXT NOT NULL,
    "currentAddress" TEXT NOT NULL,
    "currentCity" TEXT NOT NULL,
    "currentState" TEXT NOT NULL,
    "currentZip" TEXT NOT NULL,
    "currentDuration" TEXT NOT NULL,
    "livedHereThreeYears" BOOLEAN NOT NULL DEFAULT false,
    "licenseNumber" TEXT NOT NULL,
    "licenseState" TEXT NOT NULL,
    "licenseExpiration" TEXT NOT NULL,
    "cdlClass" TEXT,
    "endorsements" TEXT,
    "restrictions" TEXT,
    "licenseImageFront" TEXT,
    "licenseImageBack" TEXT,
    "hasConvictions" BOOLEAN NOT NULL DEFAULT false,
    "convictionsDetails" TEXT,
    "hasBeenBonded" BOOLEAN NOT NULL DEFAULT false,
    "bondedDetails" TEXT,
    "canLiftFiftyLbs" BOOLEAN NOT NULL DEFAULT false,
    "hasPhysicalLimits" BOOLEAN NOT NULL DEFAULT false,
    "physicalLimitsDetails" TEXT,
    "availableWeekends" BOOLEAN NOT NULL DEFAULT false,
    "availableOvernight" BOOLEAN NOT NULL DEFAULT false,
    "expectedPay" TEXT,
    "howHeardAboutUs" TEXT,
    "emergencyContactName" TEXT,
    "emergencyContactPhone" TEXT,
    "emergencyContactRelation" TEXT,
    "referredBy" TEXT,
    "signature" TEXT,
    "signatureDate" TEXT,
    "currentEmployer" TEXT NOT NULL,
    "currentPosition" TEXT NOT NULL,
    "currentStartDate" TEXT NOT NULL,
    "currentEndDate" TEXT,
    "currentSalary" TEXT NOT NULL,
    "currentReasonForLeaving" TEXT,
    "currentSupervisorName" TEXT,
    "currentSupervisorPhone" TEXT,
    "canContactCurrentEmployer" BOOLEAN NOT NULL DEFAULT true,
    "militaryService" BOOLEAN NOT NULL DEFAULT false,
    "militaryBranch" TEXT,
    "militaryRank" TEXT,
    "militaryDates" TEXT,
    "militaryDuties" TEXT,
    "status" TEXT NOT NULL DEFAULT 'submitted',
    "notes" TEXT,
    CONSTRAINT "applications_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "addresses" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "address" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "zip" TEXT NOT NULL,
    "duration" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    CONSTRAINT "addresses_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "addresses_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "applications"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "employment" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "employer" TEXT NOT NULL,
    "position" TEXT NOT NULL,
    "startDate" TEXT NOT NULL,
    "endDate" TEXT NOT NULL,
    "salary" TEXT NOT NULL,
    "reasonForLeaving" TEXT NOT NULL,
    "supervisorName" TEXT,
    "supervisorPhone" TEXT,
    "canContact" BOOLEAN NOT NULL DEFAULT true,
    "applicationId" TEXT NOT NULL,
    CONSTRAINT "employment_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "employment_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "applications"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "accidents" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "date" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "fatalities" BOOLEAN NOT NULL DEFAULT false,
    "injuries" BOOLEAN NOT NULL DEFAULT false,
    "location" TEXT,
    "charges" TEXT,
    "applicationId" TEXT NOT NULL,
    CONSTRAINT "accidents_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "accidents_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "applications"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "violations" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "date" TEXT NOT NULL,
    "violation" TEXT NOT NULL,
    "location" TEXT NOT NULL,
    "penalty" TEXT,
    "applicationId" TEXT NOT NULL,
    CONSTRAINT "violations_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "violations_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "applications"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
